import React from "react";

var tonken = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJsb2NhbGhvc3QiLCJpYXQiOjE2NTgzMjE3MDAsImF1ZCI6Im15YWRtaW5zIiwiaWQiOjEsImlzX2FkbWluIjp0cnVlfQ.v8EHDVkOkPwsoLWbWKiL3RKuL0a9Cf3vg4vo06B6bfc';

export default tonken;